codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
        paths:
          - src/
        flags:
          - frontend

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false